import { DesignSystemMeta } from '../types.ts';

export const DESIGN_SYSTEMS: DesignSystemMeta[] = [
  {
    id: 'material',
    name: "Material Design 3",
    organization: "Google",
    category: 'tech-giant',
    categoryLabel: 'Tech Giants',
    docsUrl: 'https://m3.material.io',
    repoUrl: 'https://github.com/material-components/material-web',
    description: "Google's open-source design system featuring expressive colors, dynamic theming, pill buttons, and elevation surfaces.",
    aestheticNotes: "Pill-shaped controls (9999px radius), pastel tonal containers, floating label inputs, and ripple-style focus feedback.",
    tokens: {
      primaryColor: '#6750a4',
      borderRadius: '9999px',
      controlHeight: '40px',
      fontFamily: "'Roboto', system-ui, sans-serif",
      focusStyle: "0 0 0 3px rgba(103, 80, 164, 0.3)",
    },
    variants: {
      buttons: ["Filled", "Tonal", "Outlined", "Elevated", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"filled\">Get Started</Button>",
      input: "<TextField label=\"Email address\" variant=\"outlined\" />",
      select: "<Select label=\"Region\" options={regions} />",
      radio: "<RadioGroup name=\"plan\" value={plan} onChange={setPlan} />",
    },
  },
  {
    id: 'apple',
    name: "Human Interface Guidelines",
    organization: "Apple",
    category: 'tech-giant',
    categoryLabel: 'Tech Giants',
    docsUrl: 'https://developer.apple.com/design/human-interface-guidelines',
    repoUrl: 'https://developer.apple.com/xcode/swiftui',
    description: "Apple's unified design language for macOS, iOS, and visionOS emphasizing clarity, subtle frosted glass translucency, and SF typography.",
    aestheticNotes: "SF Pro typography, 8px rounded corners, system blue accents (#0071e3), subtle inner input shadows, and refined desktop density.",
    tokens: {
      primaryColor: '#0071e3',
      borderRadius: '8px',
      controlHeight: '32px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', sans-serif",
      focusStyle: "0 0 0 3.5px rgba(0, 113, 227, 0.4)",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tinted", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"borderedProminent\">Continue</Button>",
      input: "<TextField placeholder=\"Enter name\" roundedBorder />",
      select: "<Picker selected={region}>{regions}</Picker>",
      radio: "<RadioGroup selection={selected} />",
    },
  },
  {
    id: 'fluent',
    name: "Fluent 2 Design System",
    organization: "Microsoft",
    category: 'tech-giant',
    categoryLabel: 'Tech Giants',
    docsUrl: 'https://fluent2.microsoft.design',
    repoUrl: 'https://github.com/microsoft/fluentui',
    description: "Microsoft's cross-platform design system powering Windows 11, Microsoft 365, and Azure cloud applications.",
    aestheticNotes: "Segoe UI typography, 4px radius, double-ring focus outline, and signature bottom-line accent highlight on focused inputs.",
    tokens: {
      primaryColor: '#0078d4',
      borderRadius: '4px',
      controlHeight: '32px',
      fontFamily: "'Segoe UI', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #ffffff, 0 0 0 4px #000000",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Subtle", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button appearance=\"primary\">Save changes</Button>",
      input: "<Input appearance=\"underline\" placeholder=\"Search...\" />",
      select: "<Dropdown placeholder=\"Select an option\" />",
      radio: "<RadioGroup options={plans} />",
    },
  },
  {
    id: 'carbon',
    name: "Carbon Design System",
    organization: "IBM",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://carbondesignsystem.com',
    repoUrl: 'https://github.com/carbon-design-system/carbon',
    description: "IBM's open-source design system engineered for high-density enterprise data visualization, cloud consoles, and strict accessibility.",
    aestheticNotes: "Zero border radius (sharp 0px rectangular corners), 2x grid, bottom-border only input fields, and high-contrast blue (#0f62fe).",
    tokens: {
      primaryColor: '#0f62fe',
      borderRadius: '0px',
      controlHeight: '40px',
      fontFamily: "'IBM Plex Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0f62fe",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tertiary", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button kind=\"primary\">Deploy Cluster</Button>",
      input: "<TextInput id=\"uid\" labelText=\"User ID\" />",
      select: "<Select id=\"env\" labelText=\"Environment\" />",
      radio: "<RadioButtonGroup name=\"radio-group\" defaultSelected=\"default\" />",
    },
  },
  {
    id: 'polaris',
    name: "Shopify Polaris",
    organization: "Shopify",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://polaris.shopify.com',
    repoUrl: 'https://github.com/Shopify/polaris',
    description: "The gold standard merchant design system crafted for complex e-commerce administration, billing, and inventory workflows.",
    aestheticNotes: "Inter typography, Merchant emerald green (#008060), soft 8px radii, subtle inset button shadows, and crystal-clear form helper text.",
    tokens: {
      primaryColor: '#008060',
      borderRadius: '8px',
      controlHeight: '36px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'San Francisco', Roboto, sans-serif",
      focusStyle: "0 0 0 2px #2c6ecb",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Plain", "Critical"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Save product</Button>",
      input: "<TextField label=\"Store domain\" autoComplete=\"off\" />",
      select: "<Select label=\"Fulfillment method\" options={options} />",
      radio: "<RadioButton label=\"Free shipping\" checked={selected} />",
    },
  },
  {
    id: 'atlassian',
    name: "Atlassian Design System",
    organization: "Atlassian",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://atlassian.design',
    repoUrl: 'https://bitbucket.org/atlassian/atlassian-frontend',
    description: "The battle-tested design system behind Jira, Confluence, and Bitbucket built for collaborative team productivity.",
    aestheticNotes: "Charlie/Segoe typography, Jira blue (#0052cc), compact 3px radius, neutral subdued backgrounds (#091e420f), and 2px focus outlines.",
    tokens: {
      primaryColor: '#0052cc',
      borderRadius: '3px',
      controlHeight: '32px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      focusStyle: "0 0 0 2px #4c9aff",
    },
    variants: {
      buttons: ["Primary", "Default", "Subtle", "Warning"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button appearance=\"primary\">Create issue</Button>",
      input: "<Textfield name=\"summary\" placeholder=\"Issue summary\" />",
      select: "<Select placeholder=\"Choose assignee\" />",
      radio: "<RadioGroup options={priorities} />",
    },
  },
  {
    id: 'primer',
    name: "GitHub Primer",
    organization: "GitHub",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://primer.style',
    repoUrl: 'https://github.com/primer/react',
    description: "GitHub's design system powering github.com, pull requests, code reviews, and developer CLI tools.",
    aestheticNotes: "6px radius, GitHub green (#1f883d) primary, light gray border (#d0d7de) with subtle 1px bottom drop shadow on secondary buttons.",
    tokens: {
      primaryColor: '#1f883d',
      borderRadius: '6px',
      controlHeight: '32px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif",
      focusStyle: "0 0 0 3px rgba(9, 105, 218, 0.3)",
    },
    variants: {
      buttons: ["Primary", "Default", "Invisible", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Merge pull request</Button>",
      input: "<TextInput placeholder=\"Repository name\" />",
      select: "<Select>{branches}</Select>",
      radio: "<RadioGroup name=\"visibility\" />",
    },
  },
  {
    id: 'spectrum',
    name: "Adobe Spectrum",
    organization: "Adobe",
    category: 'tech-giant',
    categoryLabel: 'Tech Giants',
    docsUrl: 'https://spectrum.adobe.com',
    repoUrl: 'https://github.com/adobe/react-spectrum',
    description: "Adobe's design system powering Photoshop Web, Illustrator, Creative Cloud, and Experience Cloud suites.",
    aestheticNotes: "Adobe Clean font, 16px pill or 4px radius, Spectrum blue (#0265dc), quiet variants, and AAA accessible focus rings.",
    tokens: {
      primaryColor: '#0265dc',
      borderRadius: '16px',
      controlHeight: '32px',
      fontFamily: "'Adobe Clean', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #ffffff, 0 0 0 4px #0265dc",
    },
    variants: {
      buttons: ["Accent", "Primary", "Secondary", "Negative"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"accent\">Export asset</Button>",
      input: "<TextField label=\"Canvas width\" />",
      select: "<Picker label=\"Color space\">{items}</Picker>",
      radio: "<RadioGroup label=\"Blend mode\" />",
    },
  },
  {
    id: 'salesforce',
    name: "Lightning Design System (SLDS)",
    organization: "Salesforce",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://www.lightningdesignsystem.com',
    repoUrl: 'https://github.com/salesforce-ux/design-system',
    description: "The enterprise CRM design system powering Salesforce Service Cloud, Sales Cloud, and Lightning Web Components.",
    aestheticNotes: "Salesforce Sans, Salesforce blue (#0176d3), 4px border radius, clear required field asterisks, and neutral borders (#747474).",
    tokens: {
      primaryColor: '#0176d3',
      borderRadius: '4px',
      controlHeight: '32px',
      fontFamily: "'Salesforce Sans', -apple-system, sans-serif",
      focusStyle: "0 0 3px #0176d3",
    },
    variants: {
      buttons: ["Brand", "Neutral", "Outline-Brand", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"brand\">Convert Lead</Button>",
      input: "<Input label=\"Account Name\" required />",
      select: "<Combobox label=\"Stage\" options={stages} />",
      radio: "<RadioGroup name=\"rating\" />",
    },
  },
  {
    id: 'ant',
    name: "Ant Design",
    organization: "Ant Group",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://ant.design',
    repoUrl: 'https://github.com/ant-design/ant-design',
    description: "Enterprise-class UI design language and React component library widely adopted across Asia and global fintech.",
    aestheticNotes: "Ant tech blue (#1677ff), 6px radius, subtle bottom drop shadow on primary buttons, dashed variant, and click wave animations.",
    tokens: {
      primaryColor: '#1677ff',
      borderRadius: '6px',
      controlHeight: '32px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      focusStyle: "0 0 0 2px rgba(5, 145, 255, 0.1)",
    },
    variants: {
      buttons: ["Primary", "Default", "Dashed", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button type=\"primary\">Submit Query</Button>",
      input: "<Input placeholder=\"Enter keyword\" allowClear />",
      select: "<Select defaultValue=\"lucy\" style={{ width: 120 }} />",
      radio: "<Radio.Group onChange={onChange} value={value} />",
    },
  },
  {
    id: 'chakra',
    name: "Chakra UI",
    organization: "Chakra UI Team",
    category: 'modern-react',
    categoryLabel: 'Modern React',
    docsUrl: 'https://chakra-ui.com',
    repoUrl: 'https://github.com/chakra-ui/chakra-ui',
    description: "Simple, modular, and accessible component library giving developers the building blocks to build React applications fast.",
    aestheticNotes: "Teal brand color (#319795), 6px radius, 40px height, solid/outline/ghost variants, and thick translucent focus rings.",
    tokens: {
      primaryColor: '#319795',
      borderRadius: '6px',
      controlHeight: '40px',
      fontFamily: "system-ui, -apple-system, sans-serif",
      focusStyle: "0 0 0 3px rgba(49, 151, 149, 0.4)",
    },
    variants: {
      buttons: ["Solid", "Outline", "Ghost", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button colorScheme=\"teal\">Join workspace</Button>",
      input: "<Input placeholder=\"Basic usage\" size=\"md\" />",
      select: "<Select placeholder=\"Select option\">{opts}</Select>",
      radio: "<RadioGroup defaultValue=\"1\"><HStack>{radios}</HStack></RadioGroup>",
    },
  },
  {
    id: 'mantine',
    name: "Mantine",
    organization: "Mantine Team",
    category: 'modern-react',
    categoryLabel: 'Modern React',
    docsUrl: 'https://mantine.dev',
    repoUrl: 'https://github.com/mantinedev/mantine',
    description: "A fully featured React components library with native dark mode support, light/filled/subtle variants, and rich hooks.",
    aestheticNotes: "Mantine blue (#228be6), 8px border radius, 36px height, signature 'light' tinted background variant, and crisp input borders.",
    tokens: {
      primaryColor: '#228be6',
      borderRadius: '8px',
      controlHeight: '36px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      focusStyle: "0 0 0 2px #228be6",
    },
    variants: {
      buttons: ["Filled", "Light", "Outline", "Subtle"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"filled\" color=\"blue\">Save changes</Button>",
      input: "<TextInput label=\"Username\" placeholder=\"Your name\" />",
      select: "<Select label=\"Framework\" data={['React', 'Vue']} />",
      radio: "<Radio.Group value={val} label=\"Select role\" />",
    },
  },
  {
    id: 'radix',
    name: "Radix Themes",
    organization: "WorkOS / Radix",
    category: 'modern-react',
    categoryLabel: 'Modern React',
    docsUrl: 'https://www.radix-ui.com/themes',
    repoUrl: 'https://github.com/radix-ui/themes',
    description: "An open-source component library optimized for fast development, easy maintenance, and accessible modern interfaces.",
    aestheticNotes: "Indigo/violet (#3e63dd), 6px radius, soft translucent pastel surfaces, surface variant with subtle border, and refined spacing.",
    tokens: {
      primaryColor: '#3e63dd',
      borderRadius: '6px',
      controlHeight: '32px',
      fontFamily: "system-ui, -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #3e63dd",
    },
    variants: {
      buttons: ["Solid", "Soft", "Surface", "Outline"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"solid\" color=\"indigo\">Invite member</Button>",
      input: "<TextField.Root placeholder=\"Search members\u2026\" />",
      select: "<Select.Root defaultValue=\"apple\">{items}</Select.Root>",
      radio: "<RadioGroup.Root defaultValue=\"1\" />",
    },
  },
  {
    id: 'shadcn',
    name: "shadcn/ui",
    organization: "shadcn",
    category: 'modern-react',
    categoryLabel: 'Modern React',
    docsUrl: 'https://ui.shadcn.com',
    repoUrl: 'https://github.com/shadcn-ui/ui',
    description: "Beautifully designed components built with Radix UI and Tailwind CSS that you can copy and paste into your apps.",
    aestheticNotes: "Zinc/slate monochrome palette, 8px radius (0.5rem), high-contrast black/white primary (#18181b), and double offset focus rings.",
    tokens: {
      primaryColor: '#18181b',
      borderRadius: '8px',
      controlHeight: '36px',
      fontFamily: "system-ui, -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #ffffff, 0 0 0 4px #18181b",
    },
    variants: {
      buttons: ["Default", "Secondary", "Outline", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"default\">Deploy Project</Button>",
      input: "<Input type=\"email\" placeholder=\"Email\" />",
      select: "<Select><SelectTrigger>{val}</SelectTrigger></Select>",
      radio: "<RadioGroup defaultValue=\"comfortable\">{items}</RadioGroup>",
    },
  },
  {
    id: 'eui',
    name: "Elastic UI (EUI)",
    organization: "Elastic",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://eui.elastic.co',
    repoUrl: 'https://github.com/elastic/eui',
    description: "The design system framework behind Kibana and Elasticsearch, built for high-density telemetry, search, and observability.",
    aestheticNotes: "Inter font, Elastic teal/blue (#006bb4), 4px radius, compact 32px height, and dense data-oriented filter controls.",
    tokens: {
      primaryColor: '#006bb4',
      borderRadius: '4px',
      controlHeight: '32px',
      fontFamily: "Inter, -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #006bb4",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Warning", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<EuiButton fill color=\"primary\">Run query</EuiButton>",
      input: "<EuiFieldText placeholder=\"KQL query...\" />",
      select: "<EuiSelect options={options} />",
      radio: "<EuiRadioGroup options={radios} idSelected={id} />",
    },
  },
  {
    id: 'fiori',
    name: "SAP Fiori",
    organization: "SAP",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://experience.sap.com/fiori-design-web',
    repoUrl: 'https://github.com/SAP/ui5-webcomponents',
    description: "SAP's enterprise design system powering S/4HANA, enterprise ERP systems, supply chains, and business suites worldwide.",
    aestheticNotes: "SAP 72 typography, Morning Horizon corporate blue (#0854a0), 4px radius, and cozy business data controls.",
    tokens: {
      primaryColor: '#0854a0',
      borderRadius: '4px',
      controlHeight: '36px',
      fontFamily: "'72', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0854a0",
    },
    variants: {
      buttons: ["Emphasized", "Standard", "Transparent", "Attention"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<ui5-button design=\"Emphasized\">Approve PO</ui5-button>",
      input: "<ui5-input placeholder=\"Purchase order number\" />",
      select: "<ui5-select>{items}</ui5-select>",
      radio: "<ui5-radio-button text=\"Express Delivery\" />",
    },
  },
  {
    id: 'govuk',
    name: "GOV.UK Design System",
    organization: "UK Government GDS",
    category: 'government',
    categoryLabel: 'Government & Civic',
    docsUrl: 'https://design-system.service.gov.uk',
    repoUrl: 'https://github.com/alphagov/govuk-frontend',
    description: "The benchmark government digital service design system trusted across hundreds of UK public sector services.",
    aestheticNotes: "Zero border radius (sharp rectangular), heavy 2px black borders, Start Green button (#00703c) with bottom bevel, and iconic yellow focus highlight.",
    tokens: {
      primaryColor: '#00703c',
      borderRadius: '0px',
      controlHeight: '40px',
      fontFamily: "'GDS Transport', Arial, sans-serif",
      focusStyle: "0 0 0 3px #ffdd00, 0 0 0 6px #0b0c0c",
    },
    variants: {
      buttons: ["Start (Green)", "Secondary", "Warning"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button isStartButton>Start now</Button>",
      input: "<Input id=\"nin\" label={{ text: 'National Insurance number' }} />",
      select: "<Select id=\"sort\" items={items} />",
      radio: "<Radios name=\"whereDoYouLive\" items={options} />",
    },
  },
  {
    id: 'uswds',
    name: "U.S. Web Design System",
    organization: "U.S. GSA",
    category: 'government',
    categoryLabel: 'Government & Civic',
    docsUrl: 'https://designsystem.digital.gov',
    repoUrl: 'https://github.com/uswds/uswds',
    description: "Federal open-source design system supporting Section 508 accessibility compliance across federal agency websites.",
    aestheticNotes: "Public Sans typography, Federal blue (#005ea2), 4px radius, 40px height, and clear accessible 4px focus rings.",
    tokens: {
      primaryColor: '#005ea2',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "'Public Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 4px #2491ff",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Outline", "Accent-Cool"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button type=\"button\">Submit application</Button>",
      input: "<TextInput id=\"ssn\" name=\"ssn\" type=\"text\" />",
      select: "<Dropdown id=\"state\" name=\"state\" options={states} />",
      radio: "<Radio id=\"historical\" name=\"presidential\" />",
    },
  },
  {
    id: 'mozilla',
    name: "Mozilla Protocol",
    organization: "Mozilla",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://protocol.mozilla.org',
    repoUrl: 'https://github.com/mozilla/protocol',
    description: "Mozilla's design system powering mozilla.org, Firefox product pages, and open web initiatives.",
    aestheticNotes: "Metropolis typography, Firefox blue (#0060df), punchy 4px radius, and high-contrast web standards aesthetics.",
    tokens: {
      primaryColor: '#0060df',
      borderRadius: '4px',
      controlHeight: '38px',
      fontFamily: "'Metropolis', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0a84ff, 0 0 0 4px rgba(10,132,255,0.3)",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Ghost"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Download Firefox</Button>",
      input: "<Input placeholder=\"Enter your email\" />",
      select: "<Select name=\"locale\" options={locales} />",
      radio: "<RadioGroup name=\"frequency\" />",
    },
  },
  {
    id: 'ubuntu',
    name: "Ubuntu Vanilla Framework",
    organization: "Canonical",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://vanillaframework.io',
    repoUrl: 'https://github.com/canonical/vanilla-framework',
    description: "Canonical's extensible CSS framework powering Ubuntu Linux portal, Snapcraft, and MAAS datacenter consoles.",
    aestheticNotes: "Ubuntu font, Canonical orange (#e95420), aubergine (#77216f), minimal 2px radius, and clean server-grade utility.",
    tokens: {
      primaryColor: '#e95420',
      borderRadius: '2px',
      controlHeight: '36px',
      fontFamily: "'Ubuntu', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #e95420",
    },
    variants: {
      buttons: ["Positive", "Default", "Brand", "Negative"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button class=\"p-button--positive\">Install package</button>",
      input: "<input type=\"text\" class=\"p-form-validation__input\" />",
      select: "<select class=\"p-form-validation__input\">{opts}</select>",
      radio: "<input type=\"radio\" class=\"p-radio__input\" />",
    },
  },
  {
    id: 'patternfly',
    name: "Red Hat PatternFly",
    organization: "Red Hat",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://www.patternfly.org',
    repoUrl: 'https://github.com/patternfly/patternfly-react',
    description: "Red Hat's open source design system built for enterprise cloud consoles like OpenShift, Ansible, and Fedora.",
    aestheticNotes: "Red Hat Text font, Red Hat blue (#06c), 3px radius, active bottom-border highlight on input focus, and technical clarity.",
    tokens: {
      primaryColor: '#0066cc',
      borderRadius: '3px',
      controlHeight: '36px',
      fontFamily: "'Red Hat Text', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0066cc",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tertiary", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Deploy container</Button>",
      input: "<TextInput value={value} type=\"text\" />",
      select: "<FormSelect value={value}>{options}</FormSelect>",
      radio: "<Radio label=\"Persistent Volume\" />",
    },
  },
  {
    id: 'base-web',
    name: "Base Web",
    organization: "Uber",
    category: 'tech-giant',
    categoryLabel: 'Tech Giants',
    docsUrl: 'https://baseweb.design',
    repoUrl: 'https://github.com/uber/baseweb',
    description: "Uber's design system built for rider, driver, and enterprise logistics platforms across high-volume mobile and web apps.",
    aestheticNotes: "Zero border radius (0px sharp geometric corners), stark monochrome black (#000000) and white, and high-impact minimalism.",
    tokens: {
      primaryColor: '#000000',
      borderRadius: '0px',
      controlHeight: '40px',
      fontFamily: "'Uber Move Text', -apple-system, sans-serif",
      focusStyle: "0 0 0 3px #000000",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tertiary"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button kind=\"primary\">Request ride</Button>",
      input: "<Input placeholder=\"Enter pickup location\" />",
      select: "<Select options={vehicles} />",
      radio: "<RadioGroup name=\"payment\" />",
    },
  },
  {
    id: 'blueprint',
    name: "Blueprint",
    organization: "Palantir",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://blueprintjs.com',
    repoUrl: 'https://github.com/palantir/blueprint',
    description: "Palantir's React-based UI toolkit optimized for building complex, data-dense web interfaces for desktop applications.",
    aestheticNotes: "Palantir cobalt blue (#106ba3), 3px radius, compact 30px height, subtle inset gradients, and rich desktop analytical ergonomics.",
    tokens: {
      primaryColor: '#106ba3',
      borderRadius: '3px',
      controlHeight: '30px',
      fontFamily: "-apple-system, 'Segoe UI', Roboto, sans-serif",
      focusStyle: "0 0 0 2px #137cbd",
    },
    variants: {
      buttons: ["Primary", "Default", "Minimal", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button intent=\"primary\" text=\"Execute analysis\" />",
      input: "<InputGroup placeholder=\"Filter dataset...\" />",
      select: "<HTMLSelect options={metrics} />",
      radio: "<RadioGroup selectedValue={val}>{radios}</RadioGroup>",
    },
  },
  {
    id: 'semantic',
    name: "Semantic UI",
    organization: "Semantic Community",
    category: 'modern-react',
    categoryLabel: 'Modern React',
    docsUrl: 'https://semantic-ui.com',
    repoUrl: 'https://github.com/Semantic-Org/Semantic-UI-React',
    description: "Classic UI component framework using human-friendly HTML conventions, natural class naming, and expressive components.",
    aestheticNotes: "Lato typography, iconic teal (#00b5ad) and royal blue (#2185d0), 4px radius, embossed buttons, and familiar web styling.",
    tokens: {
      primaryColor: '#2185d0',
      borderRadius: '4px',
      controlHeight: '38px',
      fontFamily: "'Lato', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #85b7d9",
    },
    variants: {
      buttons: ["Primary", "Teal", "Basic", "Negative"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button primary>Sign in</Button>",
      input: "<Input placeholder=\"Search tags...\" />",
      select: "<Dropdown selection options={friendOptions} />",
      radio: "<Form.Radio label=\"Small\" value=\"sm\" />",
    },
  },
  {
    id: 'porsche',
    name: "Porsche Design System",
    organization: "Porsche",
    category: 'automotive',
    categoryLabel: 'Automotive & Luxury',
    docsUrl: 'https://designsystem.porsche.com',
    repoUrl: 'https://github.com/porsche-design-system/porsche-design-system',
    description: "Porsche's official design system delivering premium luxury automotive digital experiences across web and in-car portals.",
    aestheticNotes: "Porsche Next typography, pure black (#010205) with red accent (#d5001c), 0px sharp corners, and razor-clean German luxury precision.",
    tokens: {
      primaryColor: '#010205',
      borderRadius: '0px',
      controlHeight: '40px',
      fontFamily: "'Porsche Next', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #010205",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Red Accent"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<p-button variant=\"primary\">Configure 911</p-button>",
      input: "<p-text-field-wrapper label=\"VIN Number\"><input /></p-text-field-wrapper>",
      select: "<p-select-wrapper label=\"Trim\"><select /></p-select-wrapper>",
      radio: "<p-radio-button-wrapper label=\"Manual Transmission\" />",
    },
  },
  {
    id: 'audi',
    name: "Audi Design System",
    organization: "Audi",
    category: 'automotive',
    categoryLabel: 'Automotive & Luxury',
    docsUrl: 'https://www.audi.com/ci/en/guides/user-interface/introduction.html',
    repoUrl: 'https://github.com/audi',
    description: "Audi's progressive UI system emphasizing high-tech minimalism, monochrome clarity, and luxury mobility cockpit ergonomics.",
    aestheticNotes: "Audi Type font, 0px border radius, monochrome black/white palette with Audi red (#ea0a8e) accents, and architectural minimalism.",
    tokens: {
      primaryColor: '#000000',
      borderRadius: '0px',
      controlHeight: '40px',
      fontFamily: "'Audi Type', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #000000",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Ghost"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button class=\"audi-btn-primary\">Schedule test drive</button>",
      input: "<input class=\"audi-input\" placeholder=\"Postal code\" />",
      select: "<select class=\"audi-select\">{models}</select>",
      radio: "<input type=\"radio\" class=\"audi-radio\" />",
    },
  },
  {
    id: 'pajamas',
    name: "GitLab Pajamas",
    organization: "GitLab",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://design.gitlab.com',
    repoUrl: 'https://gitlab.com/gitlab-org/gitlab-ui',
    description: "GitLab's open design system built for code review, CI/CD pipelines, security scanning, and DevOps collaboration.",
    aestheticNotes: "GitLab indigo/blue (#1f75cb), 4px radius, 32px height, calm neutral borders (#dcdcde), and developer workspace utility.",
    tokens: {
      primaryColor: '#1f75cb',
      borderRadius: '4px',
      controlHeight: '32px',
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      focusStyle: "0 0 0 2px #1f75cb",
    },
    variants: {
      buttons: ["Confirm", "Default", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<GlButton variant=\"confirm\">Merge</GlButton>",
      input: "<GlFormInput placeholder=\"Commit message\" />",
      select: "<GlFormSelect options={runners} />",
      radio: "<GlFormRadio name=\"pipeline-trigger\" />",
    },
  },
  {
    id: 'wise',
    name: "Wise Design System",
    organization: "Wise",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://wise.design',
    repoUrl: 'https://github.com/transferwise/components',
    description: "Wise's high-energy global financial design system powering frictionless multi-currency international transfers.",
    aestheticNotes: "Wise Sans, signature Forest Green (#163300) paired with Neon Lime (#9fe870), 12px rounded pill corners, and high typography punch.",
    tokens: {
      primaryColor: '#163300',
      borderRadius: '12px',
      controlHeight: '44px',
      fontFamily: "'Wise Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 3px #163300",
    },
    variants: {
      buttons: ["Forest/Lime", "Neon Lime", "Subdued"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button size=\"md\">Send money</Button>",
      input: "<Input label=\"Amount in GBP\" />",
      select: "<Select label=\"Recipient currency\" />",
      radio: "<RadioGroup name=\"fee-speed\" />",
    },
  },
  {
    id: 'mailchimp',
    name: "Mailchimp Wink",
    organization: "Mailchimp / Intuit",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://ux.mailchimp.com/patterns',
    repoUrl: 'https://github.com/mailchimp',
    description: "Mailchimp's quirky, delightful design language featuring bold black borders, retro-modern typography, and Cavendish Yellow.",
    aestheticNotes: "Means serif headers with crisp UI, Cavendish Yellow (#ffe01b), bold 2px black borders, and playful 2px offset drop shadows.",
    tokens: {
      primaryColor: '#ffe01b',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "'Means', Georgia, sans-serif",
      focusStyle: "0 0 0 3px #007c89",
    },
    variants: {
      buttons: ["Primary Yellow", "Secondary White", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button class=\"btn-primary\">Launch campaign</button>",
      input: "<input class=\"mc-input\" placeholder=\"Campaign name\" />",
      select: "<select class=\"mc-select\">{audiences}</select>",
      radio: "<input type=\"radio\" class=\"mc-radio\" />",
    },
  },
  {
    id: 'garden',
    name: "Zendesk Garden",
    organization: "Zendesk",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://garden.zendesk.com',
    repoUrl: 'https://github.com/zendeskgarden/react-components',
    description: "Zendesk's customer service design system focused on calm, organic, approachable interfaces for high-volume support agents.",
    aestheticNotes: "Zendesk Garden Kale green (#17494d), 4px radius, 36px height, and soothing calm neutral color harmony.",
    tokens: {
      primaryColor: '#17494d',
      borderRadius: '4px',
      controlHeight: '36px',
      fontFamily: "system-ui, -apple-system, sans-serif",
      focusStyle: "0 0 0 3px rgba(23, 73, 77, 0.35)",
    },
    variants: {
      buttons: ["Primary", "Basic", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button isPrimary>Solve ticket</Button>",
      input: "<Field><Label>Requester</Label><Input /></Field>",
      select: "<Dropdown><Select>{status}</Select></Dropdown>",
      radio: "<Field><Radio name=\"channel\" /></Field>",
    },
  },
  {
    id: 'orbit',
    name: "Orbit Design System",
    organization: "Kiwi.com",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://orbit.kiwi',
    repoUrl: 'https://github.com/kiwicom/orbit',
    description: "Kiwi.com's open-source design system crafted for fast, joyful, and accessible flight search and travel booking.",
    aestheticNotes: "Circular Pro font, Kiwi cyan (#00a991), 6px radius, cheerful travel booking visual clarity, and soft 44px touch targets.",
    tokens: {
      primaryColor: '#00a991',
      borderRadius: '6px',
      controlHeight: '40px',
      fontFamily: "'Circular Pro', -apple-system, sans-serif",
      focusStyle: "0 0 0 3px rgba(0, 169, 145, 0.3)",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Critical"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button type=\"primary\">Search flights</Button>",
      input: "<InputField label=\"Departure date\" />",
      select: "<Select label=\"Cabin class\" options={classes} />",
      radio: "<Radio label=\"Direct flights only\" />",
    },
  },
  {
    id: 'workday',
    name: "Workday Canvas",
    organization: "Workday",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://canvas.workday.com',
    repoUrl: 'https://github.com/Workday/canvas-kit',
    description: "Workday's accessible design system powering global enterprise HR, payroll, benefits, and financial management systems.",
    aestheticNotes: "Workday Sans, Workday bright blue (#0875e1), 4px radius, 40px height, and clear accessible corporate typography.",
    tokens: {
      primaryColor: '#0875e1',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "'Workday Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0875e1",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<PrimaryButton>Submit time off</PrimaryButton>",
      input: "<TextInput placeholder=\"Employee ID\" />",
      select: "<Select options={departments} />",
      radio: "<RadioGroup name=\"employment-type\" />",
    },
  },
  {
    id: 'leafygreen',
    name: "MongoDB LeafyGreen",
    organization: "MongoDB",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://www.mongodb.design',
    repoUrl: 'https://github.com/mongodb/leafygreen-ui',
    description: "MongoDB's design system powering MongoDB Atlas cloud console, Compass database GUI, and developer telemetry.",
    aestheticNotes: "Euclid Circular font, MongoDB spring green (#00ed64) with slate dark (#001e2b), 6px radius, and technical database clarity.",
    tokens: {
      primaryColor: '#00ed64',
      borderRadius: '6px',
      controlHeight: '36px',
      fontFamily: "'Euclid Circular A', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #016bf8",
    },
    variants: {
      buttons: ["Primary Green", "Dark Slate", "Default Outline"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Deploy cluster</Button>",
      input: "<TextInput label=\"Connection string\" />",
      select: "<Select label=\"Cluster tier\">{tiers}</Select>",
      radio: "<RadioGroup name=\"provider\" />",
    },
  },
  {
    id: 'cloudscape',
    name: "AWS Cloudscape",
    organization: "Amazon Web Services",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://cloudscape.design',
    repoUrl: 'https://github.com/cloudscape-design/components',
    description: "AWS's official open-source design system built for the AWS Management Console, high-density DevOps tables, and cloud management.",
    aestheticNotes: "Open Sans, AWS console blue (#0972d3), 4px radius, compact 32px height, double-ring focus, and high-density resource controls.",
    tokens: {
      primaryColor: '#0972d3',
      borderRadius: '4px',
      controlHeight: '32px',
      fontFamily: "'Open Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #ffffff, 0 0 0 4px #0972d3",
    },
    variants: {
      buttons: ["Primary", "Normal", "Link"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Launch instance</Button>",
      input: "<Input value={value} placeholder=\"Search VPCs\" />",
      select: "<Select selectedOption={selected} options={regions} />",
      radio: "<RadioGroup items={instanceTypes} />",
    },
  },
  {
    id: 'paste',
    name: "Twilio Paste",
    organization: "Twilio",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://paste.twilio.design',
    repoUrl: 'https://github.com/twilio-labs/paste',
    description: "Twilio's accessible design system built for omnichannel customer engagement, telephony portals, and communications APIs.",
    aestheticNotes: "Twilio Sans, Twilio brand blue (#0263e0), 4px radius, 36px height, and radical focus ring contrast for high trust.",
    tokens: {
      primaryColor: '#0263e0',
      borderRadius: '4px',
      controlHeight: '36px',
      fontFamily: "'Twilio Sans', -apple-system, sans-serif",
      focusStyle: "0 0 0 3px #0263e0",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button variant=\"primary\">Buy phone number</Button>",
      input: "<Input id=\"webhook\" type=\"text\" />",
      select: "<Select id=\"country\">{countries}</Select>",
      radio: "<RadioGroup name=\"voice-method\" />",
    },
  },
  {
    id: 'vitamin',
    name: "Decathlon Vitamin",
    organization: "Decathlon",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://vitamin.decathlon.design',
    repoUrl: 'https://github.com/Decathlon/vitamin-web',
    description: "Decathlon's dynamic athletic design system powering sports retail across 60+ countries and thousands of retail stores.",
    aestheticNotes: "Roboto font, Decathlon electric blue (#0082c3), 4px radius, energetic sports retail styling, and dynamic high visibility.",
    tokens: {
      primaryColor: '#0082c3',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "'Roboto', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0082c3",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Ghost"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<VtmnButton variant=\"primary\">Add to cart</VtmnButton>",
      input: "<VtmnTextInput placeholder=\"Shoe size\" />",
      select: "<VtmnSelect options={sports} />",
      radio: "<VtmnRadioButton name=\"pickup-method\" />",
    },
  },
  {
    id: 'backstage',
    name: "Spotify Backstage",
    organization: "Spotify",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://backstage.io',
    repoUrl: 'https://github.com/backstage/backstage',
    description: "Spotify's open platform for building internal developer portals, microservice catalogs, and infrastructure orchestration.",
    aestheticNotes: "Spotify green (#1db954) on dark slate (#121212) or clean light, 4px radius, 36px height, and clear developer tooling ergonomics.",
    tokens: {
      primaryColor: '#1db954',
      borderRadius: '4px',
      controlHeight: '36px',
      fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
      focusStyle: "0 0 0 2px #1db954",
    },
    variants: {
      buttons: ["Primary Green", "Dark Secondary", "Text"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button color=\"primary\" variant=\"contained\">Register component</Button>",
      input: "<TextField label=\"Repository URL\" />",
      select: "<Select label=\"Owner team\">{teams}</Select>",
      radio: "<RadioGroup name=\"lifecycle-stage\" />",
    },
  },
  {
    id: 'cedar',
    name: "REI Cedar",
    organization: "REI Co-op",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://cedar.rei.com',
    repoUrl: 'https://github.com/rei/cedar',
    description: "REI Co-op's outdoor recreation design system built with warm nature tones, accessible co-op values, and outdoor gear shopping.",
    aestheticNotes: "Stuart serif paired with clean sans, Cedar evergreen (#2b6636), 4px radius, 40px height, and earthy organic warmth.",
    tokens: {
      primaryColor: '#2b6636',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "'Stuart', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #2b6636",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tertiary"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<CdrButton modifier=\"primary\">Find trailhead</CdrButton>",
      input: "<CdrInput label=\"National park\" />",
      select: "<CdrSelect label=\"Tent capacity\" />",
      radio: "<CdrRadio name=\"membership-tier\" />",
    },
  },
  {
    id: 'thumbprint',
    name: "Thumbprint",
    organization: "Thumbtack",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://thumbprint.design',
    repoUrl: 'https://github.com/thumbtack/thumbprint',
    description: "Thumbtack's design system powering the local home services marketplace connecting millions of customers with pros.",
    aestheticNotes: "Thumbtack blue (#009fd9), 4px radius, 40px height, approachable consumer styling, and friendly clear microcopy.",
    tokens: {
      primaryColor: '#009fd9',
      borderRadius: '4px',
      controlHeight: '40px',
      fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
      focusStyle: "0 0 0 2px #009fd9",
    },
    variants: {
      buttons: ["Primary", "Secondary", "Tertiary"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<Button theme=\"primary\">Request quotes</Button>",
      input: "<TextInput placeholder=\"ZIP code\" />",
      select: "<Select options={categories} />",
      radio: "<Radio name=\"project-urgency\" />",
    },
  },
  {
    id: 'nord',
    name: "Nord Health",
    organization: "Nordhealth",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://nordhealth.design',
    repoUrl: 'https://github.com/nordhealth/nordcomponents',
    description: "Nordhealth's design system engineered for clinical electronic health records (EHR), veterinary software, and medical safety.",
    aestheticNotes: "Inter typography, clinical deep teal (#0e8a8a), 6px radius, 36px height, and quiet medical-grade clarity.",
    tokens: {
      primaryColor: '#0e8a8a',
      borderRadius: '6px',
      controlHeight: '36px',
      fontFamily: "Inter, -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0e8a8a",
    },
    variants: {
      buttons: ["Primary", "Default", "Danger"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<nord-button variant=\"primary\">Save patient note</nord-button>",
      input: "<nord-input label=\"Patient ID\" />",
      select: "<nord-select label=\"Dosage form\">{options}</nord-select>",
      radio: "<nord-radio label=\"Active Prescription\" />",
    },
  },
  {
    id: 'origami',
    name: "FT Origami",
    organization: "Financial Times",
    category: 'enterprise',
    categoryLabel: 'Enterprise & Cloud',
    docsUrl: 'https://origami.ft.com',
    repoUrl: 'https://github.com/Financial-Times/origami',
    description: "Financial Times' design system powering ft.com, market intelligence portals, and international financial journalism.",
    aestheticNotes: "Financier Display serif headers, FT claret (#990f3d) on iconic FT paper pink (#fff1e5), 0px sharp rectangular corners, and broadsheet elegance.",
    tokens: {
      primaryColor: '#990f3d',
      borderRadius: '0px',
      controlHeight: '38px',
      fontFamily: "'Financier Display', Georgia, serif",
      focusStyle: "0 0 0 2px #990f3d",
    },
    variants: {
      buttons: ["Primary Claret", "Paper Pink Secondary", "Inverse"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button class=\"o-buttons o-buttons--primary\">Read market report</button>",
      input: "<input class=\"o-forms-input__text\" placeholder=\"Ticker or equity\" />",
      select: "<select class=\"o-forms-input__select\">{markets}</select>",
      radio: "<input type=\"radio\" class=\"o-forms-input__radio\" />",
    },
  },
  {
    id: 'backpack',
    name: "Skyscanner Backpack",
    organization: "Skyscanner",
    category: 'e-commerce',
    categoryLabel: 'E-Commerce',
    docsUrl: 'https://backpack.github.io',
    repoUrl: 'https://github.com/skyscanner/backpack',
    description: "Skyscanner's travel design system powering flight, hotel, and car rental discovery for over 100 million monthly travelers.",
    aestheticNotes: "Skyscanner sky blue (#0770e3), 8px border radius, 40px height, clean travel booking buttons, and crisp form validation.",
    tokens: {
      primaryColor: '#0770e3',
      borderRadius: '8px',
      controlHeight: '40px',
      fontFamily: "'Skyscanner Relative', -apple-system, sans-serif",
      focusStyle: "0 0 0 2px #0770e3",
    },
    variants: {
      buttons: ["Featured", "Secondary", "Destructive"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<BpkButton>Search cheap flights</BpkButton>",
      input: "<BpkInput id=\"dest\" placeholder=\"Destination city\" />",
      select: "<BpkSelect id=\"cabin\">{cabins}</BpkSelect>",
      radio: "<BpkRadio name=\"trip-type\" label=\"Round trip\" />",
    },
  },
  {
    id: 'photon',
    name: "Firefox Photon",
    organization: "Mozilla",
    category: 'developer-tools',
    categoryLabel: 'Developer Tools',
    docsUrl: 'https://design.firefox.com/photon',
    repoUrl: 'https://github.com/FirefoxUX/photon',
    description: "The classic Firefox browser UI design system engineered for browser toolbars, tab chrome, and desktop customization.",
    aestheticNotes: "Photon blue (#0060df), 2px radius, compact 32px height, and authentic browser chrome ergonomics.",
    tokens: {
      primaryColor: '#0060df',
      borderRadius: '2px',
      controlHeight: '32px',
      fontFamily: "-apple-system, 'Segoe UI', sans-serif",
      focusStyle: "0 0 0 2px #0a84ff",
    },
    variants: {
      buttons: ["Primary", "Default", "Micro"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button class=\"photon-btn-primary\">Customize toolbar</button>",
      input: "<input class=\"photon-input\" placeholder=\"Search bookmarks\" />",
      select: "<select class=\"photon-select\">{options}</select>",
      radio: "<input type=\"radio\" class=\"photon-radio\" />",
    },
  },
  {
    id: 'win98',
    name: "98.css (Classic Retro)",
    organization: "Retro Community",
    category: 'specialty-retro',
    categoryLabel: 'Specialty & Retro',
    docsUrl: 'https://jdan.github.io/98.css',
    repoUrl: 'https://github.com/jdan/98.css',
    description: "Authentic pixel-accurate implementation of Windows 95/98 desktop operating system controls and beveled UI dialogs.",
    aestheticNotes: "MS Sans Serif font, battleship gray (#c0c0c0), 0px radius with 3D beveled borders (top-left white, bottom-right black), and 24px height.",
    tokens: {
      primaryColor: '#000080',
      borderRadius: '0px',
      controlHeight: '24px',
      fontFamily: "'MS Sans Serif', Tahoma, sans-serif",
      focusStyle: "1px dotted #000000",
    },
    variants: {
      buttons: ["Default 3D", "Pressed", "Disabled"],
      inputs: ['Default', 'With Label & Helper', 'Placeholder', 'Filled', 'Error', 'Disabled'],
      selects: ['Default', 'Pre-selected', 'Error', 'Disabled'],
      radios: ['Unselected', 'Selected', 'Disabled Unselected', 'Disabled Selected', 'Interactive Group'],
    },
    canonicalCode: {
      button: "<button>OK</button>",
      input: "<input type=\"text\" value=\"C:\\WINDOWS\\SYSTEM32\" />",
      select: "<select><option>Floppy (A:)</option></select>",
      radio: "<input type=\"radio\" id=\"radio1\" /><label for=\"radio1\">Enable dial-up</label>",
    },
  },
];
