import { UISystem } from '../../schemas/uiSystem.js';

export const parkUi: UISystem = {
  id: 'park-ui',
  name: 'Park UI',
  organization: 'Park UI Community',
  description: 'A modern, styled component system built on Ark UI primitives and Panda CSS / Tailwind CSS, delivering a multi-framework (React, Vue, Solid) alternative to shadcn/ui with first-class state machines and design tokens.',
  category: 'styled',
  secondaryCategories: ['saas', 'developer-tool', 'accessibility-focused'],
  frameworks: ['react', 'vue', 'solid', 'svelte'],
  stylingApproach: 'utility-classes',
  packageNames: ['@ark-ui/react', '@pandacss/dev'],
  docsUrl: 'https://park-ui.com',
  repositoryUrl: 'https://github.com/chakra-ui/park-ui',
  license: 'MIT',
  accessibility: {
    wcagLevel: 'AA',
    keyboardNav: true,
    screenReaderTested: true,
    ariaCompliant: true,
    notes: 'Backed by Zag.js state machines for robust keyboard and focus accessibility.'
  },
  darkMode: true,
  rtlSupport: true,
  designTokens: {
    available: true,
    format: 'Panda CSS / Tailwind Design Tokens',
    packageName: '@park-ui/panda-preset'
  },
  icons: {
    available: false,
    name: 'Lucide Icons'
  },
  maturity: 'production',
  opinionatedLevel: 'moderately-opinionated',
  density: 'comfortable',
  aesthetic: 'Crisp, contemporary SaaS aesthetic inspired by Panda CSS and Ark UI with multi-framework parity.',
  noveltyLevel: 'hidden-gem',
  bestFor: [
    'Multi-framework teams needing a shadcn-like experience in Vue, Solid, or Svelte',
    'Projects built with Panda CSS or modern Tailwind CSS',
    'Modern SaaS applications wanting state-machine powered reliability'
  ],
  avoidFor: [
    'Traditional monolithic jQuery or AngularJS legacy codebases'
  ],
  strengths: [
    'The premier multi-framework (React, Vue, Solid) component preset',
    'State machine driven components prevent timing/transition bugs',
    'Full theme customization with Panda CSS or Tailwind presets'
  ],
  weaknesses: [
    'Copy-paste component architecture requires initial CLI init setup'
  ],
  tags: [
    'park-ui',
    'ark-ui',
    'panda-css',
    'tailwind',
    'multi-framework',
    'react',
    'vue',
    'solid',
    'saas',
    'hidden-gem'
  ],
  installation: {
    react: {
      command: 'npx @park-ui/cli init',
      packages: ['@ark-ui/react'],
      peerDependencies: ['react', 'react-dom'],
      setupInstructions: 'Initialize Park UI with the CLI and install Panda CSS or Tailwind preset.'
    }
  },
  componentGuidance: {
    button: {
      canonicalName: 'Button',
      description: 'Park UI styled button with variant="solid" | "outline" | "ghost" | "link".',
      importExample: "import { Button } from '~/components/ui/button';\n\n<Button variant=\"solid\">Save Profile</Button>",
      docSubUrl: 'docs/react/components/button'
    }
  },
  aiInstructions: {
    principles: [
      'Import components from your local `components/ui/*` path generated by Park UI.',
      'Use Ark UI state machine props for interaction states.',
      'Use Panda CSS / Tailwind tokens for custom layout spacing.'
    ],
    forbiddenSubstitutions: ['shadcn/ui', '@mui/material'],
    themingGuide: 'Configure theme via Panda CSS preset or Tailwind config.',
    iconUsage: 'Use Lucide React / Vue / Solid icons.',
    layoutConventions: 'Combine Park UI components with styled Flex/Grid.'
  }
};
